name: mws test
favicon: null
layout_spectrum: 0.09443688509054482
typography_spectrum: 0.89328902377747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d5d5d5'
    - '#a0a0a0'
    - '#3a3a3a'
    - '#070707'
  brandStrength: 0.8649114973377436
  lightness: 0.3689759583212435
  saturation: 0.8171536447480321
  rhythmicContrast: 0.1117614759132266
purpose: []
